### ISSUE TITLE
reference of unused faces always start at f0 in the GUI

### ISSUE THREAD

**Issue by alexiscastel** [mbinelo/roribloco#2]
The name of the faces in the list of unused faces is not accurate, the list always starts at f0 and moves on incrementally even if the f0 face is associated with a boundary. As soon as a face is associated with a boundary, the list is inaccurate.

**Comment by mbinelo** [comment]
I updated the program, could you confirm if the bug is fixed?

**Comment by alexiscastel** [comment]
Fixed, awesome, thank you.
