### ISSUE TITLE
write more digits on coordinates

### ISSUE THREAD

**Issue by alexiscastel** [mbinelo/roribloco#3]
When working with wedges, blockMesh checks that the boundary face is planar, the tolerance is very low (I believe 1e-16). Currently, with coordinates using 6 digits, blockMesh kicks me out in such a situation.
Simply writing more digits in the dictionary does the trick.

**Comment by mbinelo** [comment]
Please, could you provide a project file ".blkfoam" where this problem happens?

**Comment by alexiscastel** [comment]
I am having issues reproducing this on something generic I can share.
The file below is pretty close to what I am doing except it's working just fine.
[planar_issue.zip](https://github.com/mbinelo/roribloco/files/5164197/planar_issue.zip)

I'll try messing with it some more to see if I can trigger the issue.

**Comment by mbinelo** [comment]
I updated the program, could you confirm if the bug is fixed?

**Comment by alexiscastel** [comment]
That's works, thank you.
