### ISSUE TITLE
How to move the object in the window?

### ISSUE THREAD

**Issue by bhqasx** [mbinelo/roribloco#6]
Hi, thank you first for making effort to develop this tool.

The mainblock is often out of the window when I'm inspecting it if it is very large in one dimension. Can you add some way like "shift + left mouse" to move the object?

**Comment by mbinelo** [comment]
Hi! Good to know it is helpful.
I will take a look and try to to fix it!

**Comment by mbinelo** [comment]
Hi, I just updated (version 0.4.1). I fixed a camera issue, and you can move the geometry with the right mouse button.
Please, could you confirm if the problem is fixed?

**Comment by bhqasx** [comment]
> Hi, I just updated (version 0.4.1). I fixed a camera issue, and you can move the geometry with the right mouse button.
> Please, could you confirm if the problem is fixed?

Version 0.4.1 fixed the problem. Great job!
